/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "incytcudmqiqsifntnhm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluY3l0Y3VkbXFpcXNpZm50bmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNTc0MjMsImV4cCI6MjA3NTYzMzQyM30.4lJMaK7c-d0GBHZAEZ3ZQ0fa7YZB6BJ9gOjx_bz-SaQ"